export default {
  LOGIN_SCREEN: 'LoginScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  HOME_SCREEN: 'HomeScreen',
  ABOUT_SCREEN: 'AboutScreen',
  MAIN_TAB_ROUTES: 'MainTabRoutes',
  DETAIL_PRODUCT_ROUTES: 'DetailProductScreen',
  REAL_TIME_DATABASE: 'RealTimeDatabase',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  DETAIL_MOVIE_SCREEN: 'DetailMovieScreen',
  All_Movies_List: 'AllMoviesList',
  Similar_Movie_Detail_Screen: 'SimilarMovieDetailScreen',
  All_Similar_Movies_Screen: 'AllSimilarMoviesScreen',
  All_Catogory_Movie_Screen: 'AllCatogoryMovieScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  Notification_SCREEN: 'NotificationScreen',
  SEARCH_SCREEN: 'SearchScreen',
};
