export default {
  LOGIN_SCREEN: 'LoginScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  HOME_SCREEN: 'HomeScreen',
  ABOUT_SCREEN: 'AboutScreen',
  MAIN_TAB_ROUTES: 'MainTabRoutes',
  DETAIL_PRODUCT_ROUTES: 'DetailProductScreen',
  REAL_TIME_DATABASE: 'RealTimeDatabase',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  DETAIL_MOVIE_SCREEN: 'DetailMovieScreen',
  All_Movies_List: 'AllMoviesList',
  Similar_Movie_Detail_Screen: 'SimilarMovieDetailScreen',
  All_Similar_Movies_Screen: 'AllSimilarMoviesScreen',
  All_Catogory_Movie_Screen: 'AllCatogoryMovieScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  Notification_SCREEN: 'NotificationScreen',
  SEARCH_SCREEN: 'SearchScreen',
  Movie_Collection_Screen: 'MovieCollectionScreen',
  Show_Movie_Collection_Screen: 'ShowMovieCollectionScreen',
  TODO_SCREEN: 'TodoScreen',
  CREATE_TODO_SCREEN: 'CreateTodoScreen',
  UPDATE_TODO_SCREEN: 'UpdateTodoScreen',
  Find_Movie_by_year_SCREEN: 'FindMovieByYearScreen',
  SEARCH_PEXELS_SCREEN: 'SearchPexelsPhotosScreen',
  Detail_Photo_Screen: 'DetailPhotoScreen',
  FlashList_Testing_Screen: 'FlashListTestingScreen',
  Search_Pexels_Videos: 'SearchPexelsVideos',
  Pexels_Videos_Screen: 'PexelsVideosScreen',
  Show_Video_Screen: 'ShowVideoScreen',
  Pexel_Collection_Screen: 'PexelCollectionScreen',
  Photo_Editing_Screen: 'PhotoEditingScreen',
  Favorite_Movie_Screen: 'FavoriteMovieScreen',
  Show_All_Trading_Movies_Screen: 'ShowAllTradingMoviesScreen',
  Trending_Tv_Serial_Screen: 'TrendingTvSerialScreen',
  All_Users_List_Screen: 'AllUsersListScreen',
  Chat_Screen: 'ChatScreen',
  Now_Playing_Movies_Screen: 'NowPlayingMoviesScreen',
  Search_Multi_Screen: 'SearchMultiScreen',
  WeatherAppHomeScreen: 'WeatherAppHomeScreen',
  Top_News_Screen: 'TopNewsScreen',
  Detail_News_Screen: 'DetailNewsScreen',
  Search_News_Screen: 'SearchNewsScreen',
  Rotton_Tomatos_Screen: 'RottonTomatosScreen',
  Food_Recipe_Home_Screen: 'FoodRecipeHomeScreen',
  Detail_Food_Recipe_Screen: 'DetailFoodRecipeScreen',
  Read_Articel_Screen: 'ReadArticelScreen',
  Coffee_GetStarted_Screen: 'CoffeeGetStartedScreen',
  Coffee_Home_Screen: 'CoffeeHomeScreen',
  Detail_Coffee_Screen: 'DetailCoffeeScreen',
  Add_Coffee_Screen: 'AddCoffeeScreen',
  Buy_Now_Coffee_Screen: 'BuyNowCoffeeScreen',
  WorkOut_Home_Screen: 'WorkOutHomeScreen',
  WorkOut_Detail_Screen: 'WorkOutDetailScreen',
  Workout_List_Screen: 'WorkoutListScreen',

  // below screens for FitnessX
  FitnessX_Onboarding_Screen: 'FitnessXOnboardingScreen',
  FitnessX_Activity_Tracker_Screen: 'FitnessXActivityTrackerScreen',

  // below screens for pixabay photos
  Pixabay_Search_Screen: 'PixabaySearchScreen',
  Pixabay_Search_Videos: 'PixabaySearchVideos',
};
